services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: smart-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${C_DB}
      POSTGRES_USER: ${C_USER}
      POSTGRES_PASSWORD: ${C_PASSWORD}
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  postgres-test:
    image: pgvector/pgvector:pg16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${T_DB}
      POSTGRES_USER: ${T_USER}
      POSTGRES_PASSWORD: ${T_PASSWORD}
    tmpfs:
      - /var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: smart-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  postgres_data:
  redis_data:
